### ISSUE TITLE
Etag needs to be quoted?

### ISSUE THREAD

**Issue by vincentbernat** [kotx/render#21]
Hey!

In `src/index.ts`, it is said that the R2 API requires etag to not be quoted. I don't find this information in the [API documentation](https://developers.cloudflare.com/r2/data-access/workers-api/workers-api-reference/#conditional-operations). Moreover, with Miniflare, etag should be left quoted, otherwise, there is no match.

**Comment by kotx** [comment]
Hi,

It seems that S3 If-Match Etags never contain quotes, even if Etags in the HTTP response do. See below screenshot.

[https://discord.com/channels/595317990191398933/940663374377783388/975306376203083796](https://discord.com/channels/595317990191398933/940663374377783388/975306376203083796)

![https://user-images.githubusercontent.com/33439542/193421116-a927e071-8a5b-4383-a1dd-90367c78e66c.png](https://user-images.githubusercontent.com/33439542/193421116-a927e071-8a5b-4383-a1dd-90367c78e66c.png)

If Miniflare doesn't work with these then it's probably a bug since it should match the Cloudflare R2 API. Or R2 isn't implementing the S3 API correctly.

**Comment by vincentbernat** [comment]
Thanks. I have opened https://github.com/cloudflare/miniflare/issues/402.
